### ISSUE TITLE
Missing logs directory

### ISSUE THREAD

**Issue by nadzorov** [bugy/script-server#108]
Hello,

launcher.py fails with following error:

`Traceback (most recent call last):
  File "./launcher.py", line 11, in <module>
    server.main()
  File "src/server.py", line 593, in main
    logging.config.dictConfig(log_config)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/Users/vn/GitHub/script-server/logs/server.log'`

**Comment by bugy** [comment]
Hi @nadzorov, thanks for the report, I've committed the fix.
