### ISSUE TITLE
Cannot start docker container

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#228]
By @aschodinnadcat (moved from another git issue)

its not start in docker :

docker run -d -p 5000:5000 
-v /scriptsserver/conf/conf.json:/app/conf/conf.json 
-v /scriptsserver/runners/:/app/conf/runners 
-v /scriptsserver/scripts/:/app/scripts/ 
--name script-server 
bugy/script-server:latest

cat /scriptsserver/conf/conf.json
{
"port": 5000,
"title": "My Script Server",
"address": "192.168.195.142"
}

while im start docker its exited :

docker start 3de316c0e603
3de316c0e603

root@ansible:/scriptsserver/conf# docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
3de316c0e603 bugy/script-server:latest "python3 launcher.py" 7 minutes ago Exited (1) 1 second ago script-server

docker logs script-server
2019-08-07 03:35:23,131 [migrations.INFO] Applying migration add_execution_info_to_log_files
2019-08-07 03:35:23,132 [migrations.INFO] Applying migration introduce_access_config
2019-08-07 03:35:23,132 [migrations.INFO] Applying migration add_user_id_to_log_files
2019-08-07 03:35:23,133 [migrations.INFO] Applying migration migrate_output_files_parameters_substitution
2019-08-07 03:35:23,136 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
2019-08-07 03:35:40,229 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
2019-08-07 03:37:44,290 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
2019-08-07 03:43:00,851 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
2019-08-07 03:43:10,530 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
2019-08-07 03:43:42,593 [asyncio.DEBUG] Using selector: EpollSelector
Traceback (most recent call last):
File "launcher.py", line 11, in 
main.main()
File "src/main.py", line 125, in main
secret)
File "src/web/server.py", line 842, in init
http_server.listen(server_config.port, address=server_config.address)
File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

But it s already start fine if i just : docker run -d -p 5000:5000 \ bugy/script-server:latest
i see a web-form but, i see scripts to execute , but they catn be executed coz of wrong path ( i suppouse that path must be in host machine, any path inside of docker container is wrong for it )

**Comment by bugy** [comment]
Hi @aschodinnadcat,

regarding `Cannot assign requested address` error: I think the problem is in your configuration file, you are trying to listen to an IP which doesn't belong to the container
`"address": "192.168.195.142"`
I would suggest removing this configuration since it hardly makes sense for a docker container

Regarding paths: you need to mount both configuration and script paths. In docker hub example, for the script path it's:
`-v /host/path/to/scripts/:/app/scripts/`
And then in a script configuration, you have to specify `/app/scripts/my_script.sh` path. Or use a relative path: `scripts/my_script.sh` (the latter one needs double-checking)
