### ISSUE TITLE
Windows + python 3.8: server start fails with NotImplementedError

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#251]
If you try to run Script server on Windows machine, using python3.8, it fails with 
```
2019-12-29 23:10:05,951 [asyncio.DEBUG] Using proactor: IocpProactor
Traceback (most recent call last):
  File "script-server\launcher.py", line 11, in <module>
    main.main()
  File "src\main.py", line 124, in main
    server.init(
  File "src\web\server.py", line 909, in init
    http_server.listen(server_config.port, address=server_config.address)
  File "Python38-32\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "Python38-32\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "Python38-32\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "Python38-32\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "Python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
```

**Comment by bugy** [comment]
The reason (and the fix) is https://github.com/tornadoweb/tornado/issues/2608
