### ISSUE TITLE
200 GET very long timings

### ISSUE THREAD

**Issue by Melodoni** [bugy/script-server#336]
Straight forward. Everything works. 

But... if i activate the Firewall (Linux Ubuntu 20.04 - IPTables) timings getting realy bad... 

`python3[33053]: 2020-09-09 11:28:46,934 [tornado.access.INFO] 200 GET /scripts (127.0.0.1) 5010.15ms`

5 Seconds to get the scripts is very long i think..

If I configure the iptables to let everything in, the log changes to somthing like this:

`python3[33053]: 2020-09-09 11:28:46,934 [tornado.access.INFO] 200 GET /scripts (127.0.0.1) 1.35ms`

My Configurations:

script-server: conf.json
```
{
        "port": 5000,
        "address": "127.0.0.1",
        "title": "Script Server",
        "ssl": {
                "key_path": "/etc/ssl/server.key",
                "cert_path": "/etc/ssl/server.cer"
                },
        "access": {
                "trusted_ips": ["BLANKED],
                "user_header_name": "X-Forwarded-User"
                },
        "logging": {
                "execution_file": "$DATE-$ID.log",
                "execution_date_format": "%y-%m-%d_%H-%M"
                 }
}
```

Apache2 Reverse Proxy conf:

```
<VirtualHost *:80>
   ServerName BLANKED
   RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<VirtualHost *:8080>
   ServerName BLANKED
   RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName BLANKED

    SSLProxyEngine on
    RequestHeader set Front-End-Https "On"
    ProxyPreserveHost On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests off

    SSLCertificateFile /etc/ssl/server.cer
    SSLCertificateKeyFile /etc/ssl/server.key

<Location />
    Include conf-available/ldap-auth.conf
    Define ScriptServerUrl https://127.0.0.1:5000/

    ProxyPass ${ScriptServerUrl}
    ProxyPassReverse ${ScriptServerUrl}
    RequestHeader edit Destination ^http: https: early
    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /(.*) wss:/$1 [P,NE]
</Location>
</VirtualHost>
```

Apache2 remoteip.conf

```
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy BLANKED (Server IP)
```

IP Tables Confiiguration with good timings:

```
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i ens19 -j ACCEPT
-A FORWARD -i ens19 -j ACCEPT
COMMIT
```

IP Tables Confiiguration with bad timings:

```
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i ens19 -j ACCEPT
-A FORWARD -i ens19 -j ACCEPT
COMMIT
```

FYI: ens19 is the network interface for the clients.

Is there somthing that I miss?

Greetings from Germany

**Comment by Melodoni** [comment]
Found somthing maybe intressting ^^

An ERROR at the beginning:

```
2020-09-09 11:26:47,508 [tornado.application.ERROR] Exception in callback functools.partial(<bound method WebSocketHandler.write_message of <web.server.ScriptConfigSocket object at 0x7f0702f7f310>>, '{"event": "initialConfig", "data": {"id": "c0469fc3-298f-4d6c-8e0f-73f04fe26138", BLANKED}]}}')
Traceback (most recent call last):
  File "/etc/scriptserver/venv/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/etc/scriptserver/venv/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2020-09-09 11:26:47,512 [tornado.access.INFO] 101 GET /scripts/BLANKED(127.0.0.1) 1.69ms
2020-09-09 11:26:52,519 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:27:28,530 [tornado.access.INFO] 101 GET /scripts/BLANKED (127.0.0.1) 1.11ms
2020-09-09 11:27:33,537 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:27:47,834 [tornado.access.INFO] 101 GET /scripts/BLANKED (127.0.0.1) 0.90ms
2020-09-09 11:27:52,841 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:28:05,769 [tornado.access.INFO] 101 GET /scripts/BLANKED (127.0.0.1) 1.23ms
2020-09-09 11:28:10,777 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:28:41,666 [tornado.access.INFO] 200 GET /index.html (127.0.0.1) 1.91ms
2020-09-09 11:28:41,710 [tornado.access.INFO] 200 GET /index-deps.css (127.0.0.1) 8.68ms
2020-09-09 11:28:41,722 [tornado.access.INFO] 200 GET /css/index.css (127.0.0.1) 3.04ms
2020-09-09 11:28:41,724 [tornado.access.INFO] 200 GET /css/bash_styles.css (127.0.0.1) 4.59ms
2020-09-09 11:28:41,742 [tornado.access.INFO] 200 GET /index.js (127.0.0.1) 22.12ms
2020-09-09 11:28:41,853 [tornado.access.INFO] 200 GET /favicon.ico (127.0.0.1) 1.82ms
2020-09-09 11:28:41,916 [tornado.access.INFO] 200 GET /b789b6e0d14b9092f8e9468ccd3e3217.png (127.0.0.1) 12.39ms
2020-09-09 11:28:41,920 [tornado.access.INFO] 200 GET /auth/info (127.0.0.1) 0.91ms
2020-09-09 11:28:41,922 [tornado.access.INFO] 200 GET /88185dcab2187b022bcb7f4773d7396e.png (127.0.0.1) 1.43ms
2020-09-09 11:28:41,923 [tornado.access.INFO] 200 GET /conf (127.0.0.1) 0.73ms
2020-09-09 11:28:46,930 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:28:46,934 [tornado.access.INFO] 200 GET /scripts (127.0.0.1) 5010.15ms
2020-09-09 11:28:46,938 [tornado.access.INFO] 200 GET /favicon.ico (127.0.0.1) 4.02ms
2020-09-09 11:28:46,940 [tornado.access.INFO] 200 GET /executions/active (127.0.0.1) 0.97ms
2020-09-09 11:28:46,966 [tornado.access.INFO] 101 GET /scripts/BLANKED (127.0.0.1) 0.85ms
2020-09-09 11:28:51,972 [script_server.audit_utils.WARNING] Could not get hostname for 10.32.152.220
2020-09-09 11:42:43,247 [tornado.access.INFO] 101 GET /scripts/Verbundene%20Zertifikate (127.0.0.1) 1.42ms
2020-09-09 11:42:48,257 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
2020-09-09 11:43:01,669 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
```

**Comment by bugy** [comment]
This looks pretty similar to https://github.com/bugy/script-server/issues/332

So, the issue seems to be there:
```
2020-09-09 11:26:47,512 [tornado.access.INFO] 101 GET /scripts/BLANKED(127.0.0.1) 1.69ms
2020-09-09 11:26:52,519 [script_server.audit_utils.WARNING] Could not get hostname for BLANKED
```
It takes 5 sec to resolve the caller hostname (and it fails in the end).
Script server is fetching hostname to give admins more audit information about the user.

@father-mande FYI

**Comment by Melodoni** [comment]
Yeah okay, Thanks :D I've fixed it and now it works fine ^^

**Comment by father-mande** [comment]
Hi,

Thanks, I have solved my configuration by adding line in /etc/hosts to resolve name easily
but it's not a long term solution ... because I can't integrate all client in /etc/hosts

I will continue to try to have a better solution.
I just appreciate to know that my problem is not only for my configuration ...
Thanks to Bugy and Melodoni ... appreciate all your efforts.

Philippe.

**Comment by Melodoni** [comment]
I've done exactly the same :D if there is any better way to solve this, go for it and show me please ^^
