### ISSUE TITLE
[bug] Launching scripts sometimes causes exception and hanging request on GUI

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#38]
Error log:
> 2016-08-11 17:25:00,831 [scriptServer.INFO] Calling script: ...
> 2016-08-11 17:25:00,851 [tornado.access.INFO] 200 POST /scripts/execute (...) 120.47ms
> Exception in thread Thread-58:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/shepilov/DEV/github/script-server/execution.py", line 176, in pipe_process_output
>     if data and (self.encoding.lower() == "utf-8"):
> AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by bugy** [comment]
Fixed cause of exception in 110a98696de60cbdcff1032301b525fd6157122a and ff52546442a747bbcd464c4a8492482c8b8af0f2
Need to fix hanging GUI also

**Comment by bugy** [comment]
Added behaviour on script output reading, that script will be killed and error will be shown to the user.
