### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by nephaste** [bugy/script-server#446]
Hi 

i am trying installing with Python 3.8
when starting launcher.py got 

```
 Traceback (most recent call last):
  File "launcher.py", line 9, in <module>
    import main
  File "src/main.py", line 8, in <module>
    import migrations.migrate
  File "src/migrations/migrate.py", line 9, in <module>
    import execution.logging
  File "src/execution/logging.py", line 7, in <module>
    from execution.execution_service import ExecutionService
  File "src/execution/execution_service.py", line 4, in <module>
    from typing import Optional, Dict, Callable, Any
  File "/share/CACHEDEV1_DATA/.qpkg/ScriptServer/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/share/CACHEDEV1_DATA/.qpkg/ScriptServer/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

pip requirement installed 

- tornado 6.1
- typing 3.7.4.3

i have no clue on how to fix it...

thanks for your help

**Comment by bugy** [comment]
Hi @nephaste, could you try uninstall typing and run it again? 
It should be a part of standard python library, not an external dependency

**Comment by nephaste** [comment]
thanks it run   :)

probably need to be removed from requirement.txt

**Comment by bugy** [comment]
Good point, thanks
