### ISSUE TITLE
link broken in runners, crash SC at start 

### ISSUE THREAD

**Issue by father-mande** [bugy/script-server#546]
Hi,
I use link in runners folder to different scripts in different places.
If a link is broken (target was removed) SC crash at start ... reason file not exist.
**===========**
Traceback (most recent call last):
  File "launcher.py", line 11, in <module>
    main.main()
  File "src/main.py", line 79, in main
    migrations.migrate.migrate(TEMP_FOLDER, CONFIG_FOLDER, SERVER_CONF_PATH, LOG_FOLDER)
  File "src/migrations/migrate.py", line 387, in migrate
    migration_descriptor.callable(context)
  File "src/migrations/migrate.py", line 269, in __migrate_bash_formatting_to_output_format
    for (conf_file, json_object, content) in _load_runner_files(context.conf_folder):
  File "src/migrations/migrate.py", line 348, in _load_runner_files
    content = file_utils.read_file(conf_file)
  File "src/utils/file_utils.py", line 63, in read_file
    with open(path, mode, newline=newline) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/runners/xxxxxxx.json'
**==========**
Is it possible to replace crash by a log message / warning or ignore it (even using a new parameter for launcher.py ?

for the moment, I work around using a shell to verify all link in runners before launching SC. 

Philippe.

**Comment by bugy** [comment]
Hi @father-mande thx for reporting. I added a quick fix, which ignores broken symlinks during migration.
