### ISSUE TITLE
No login prompt if 'Always translate English to [lang]' in Edge Chromium

### ISSUE THREAD

**Issue by agail** [bugy/script-server#591]
Hi,

Script-server version: 1.17.0-master

One of my end-users complained that his session of the script-server didn't work, all he got was a blank page.
Turns out that he accidentally activated 'Always translate English to [language]' globally.

When we removed that and cleared the cookie (for good measure) and reloaded the page, he was met by a login prompt again.

This _may_ have been resolved already in newer versions, I haven't verified.

Session log:
```2022-10-25 13:51:27,525 [tornado.access.INFO] 302 GET / (192.168.121.66) 0.75ms
2022-10-25 13:51:27,795 [tornado.application.ERROR] Uncaught exception GET /auth/info (192.168.121.66)
HTTPServerRequest(protocol='https', host='server.domain.org:6443', method='GET', uri='/auth/info', version='HTTP/1.1', remote_ip='192.168.121.66')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/app/src/web/web_utils.py", line 26, in wrapper
    user = get_user(self)
  File "/app/src/web/web_utils.py", line 35, in get_user
    user_id = identify_user(request_handler)
  File "/app/src/web/web_utils.py", line 16, in identify_user
    user_id = request_handler.application.identification.identify(request_handler)
  File "/app/src/auth/identification.py", line 31, in identify
    raise Exception('Not authenticated')
Exception: Not authenticated
2022-10-25 13:51:27,796 [tornado.access.ERROR] 500 GET /auth/info (192.168.121.66) 1.31ms
2022-10-25 13:51:27,797 [web_server.WARNING] 401 GET /conf: user is not authenticated
2022-10-25 13:51:27,797 [tornado.general.WARNING] 401 GET /conf (192.168.121.66): Not authenticated
2022-10-25 13:51:27,797 [tornado.access.WARNING] 401 GET /conf (192.168.121.66) 0.78ms
2022-10-25 13:51:27,800 [web_server.WARNING] 401 GET /scripts: user is not authenticated
2022-10-25 13:51:27,801 [tornado.general.WARNING] 401 GET /scripts (192.168.121.66): Not authenticated
2022-10-25 13:51:27,801 [tornado.access.WARNING] 401 GET /scripts (192.168.121.66) 0.93ms
2022-10-25 13:51:27,804 [web_server.WARNING] 401 GET /executions/active: user is not authenticated
2022-10-25 13:51:27,804 [tornado.general.WARNING] 401 GET /executions/active (192.168.121.66): Not authenticated
2022-10-25 13:51:27,805 [tornado.access.WARNING] 401 GET /executions/active (192.168.121.66) 0.81ms```

**Comment by bugy** [comment]
Hi @agail thanks a lot for reporting!

**Comment by bugy** [comment]
Hi @agail I made a fix, hopefully that would work. If you could test it on dev version, that would be great
This seems to be a bug, introduced in version 1.17
