### ISSUE TITLE
Script server downloads autoclean is not working if resultFiles folder doesn't exist

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#64]
It fails with an exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/shepilov/DEV/github/script-server/file_download_feature.py", line 154, in clean_results
    for user_folder in os.listdir(results_folder):
FileNotFoundError: [Errno 2] No such file or directory: 'temp/resultFiles'
```

**Comment by bugy** [comment]
Fixed, now autoclean task is checking, whether the folder exists
