### ISSUE TITLE
Unable to delete script from UI

### ISSUE THREAD

**Issue by kodifan** [bugy/script-server#663]
Hello
Im not sure that this feature is already implemented, but if button exists it should work
But it does not :)

`2023-04-27 11:49:33,296 [tornado.application.ERROR] Uncaught exception DELETE /admin/scripts/test%20multiselect 
HTTPServerRequest(protocol='https', host='xxxxx', method='DELETE', uri='/admin/scripts/test%20multiselect', version='HTTP/1.1', remote_ip='xxxx')
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1784, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "src/web/server.py", line 62, in wrapper
    return func(self, *args, **kwargs)
  File "src/web/web_utils.py", line 29, in wrapper
    return func(self, *new_args, **kwargs)
  File "src/web/server.py", line 208, in delete
    self.application.config_service.delete_config(user, script_name)
  File "src/config/config_service.py", line 151, in delete_config
    archive_file_name = _create_archive_filename(os.path.basename(path))
  File "src/config/config_service.py", line 55, in _create_archive_filename
    return f"{formatted.datetime}_{filename}.deleted"
NameError: name 'formatted' is not defined
2023-04-27 11:49:33,298 [tornado.access.ERROR] 500 DELETE /admin/scripts/test%20multiselect (xxxxx) 13.91ms`

**Comment by bugy** [comment]
Hi @kodifan it was fixed yesterday in #662, could you try the latest build, please?

**Comment by kodifan** [comment]
working like a charm :) thx again
