### ISSUE TITLE
Need help to start Script-server in unix environment 

### ISSUE THREAD

**Issue by bard7969** [bugy/script-server#684]
We have stopped script-server which was already running  by using systemctl stop command, now while running launcher.py , we are getting below errors, please help.

]/opt/script-server# ./launcher.py
2023-07-21 17:54:19,557 [root.INFO] Starting Script Server, v1.16.0
Traceback (most recent call last):
  File "./launcher.py", line 11, in <module>
    main.main()
  File "src/main.py", line 81, in main
    server_config = server_conf.from_json(SERVER_CONF_PATH, TEMP_FOLDER)
  File "src/model/server_conf.py", line 65, in from_json
    json_object = json.loads(file_content)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 20 column 1 (char 441)

**Comment by bugy** [comment]
Hey, it looks like your conf.json file is corrupted. Please check it in some json editor for syntax issues

**Comment by bard7969** [comment]
Absolutely , there was a missing comma in conf.json , after fixing its back online. Many Thanks !!
