### ISSUE TITLE
There are often exceptions after script execution on Windows

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#72]
It looks like these errors don't affect script execution itself, but it worth investigating and fixing

`2017-05-14 17:19:44,311 [tornado.general.ERROR] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 523, in _handle_events
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized
2017-05-14 17:19:44,326 [tornado.application.ERROR] Exception in callback None
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\ioloop.py", line 888, in start      handler_func(fd_obj, events)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 523, in _handle_events
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sizedException in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\buggy\Documents\script-server\execution.py", line 126, in notify_finished
    listener.finished()
  File "C:\Users\buggy\Documents\script-server\launcher.py", line 351, in finished
    web_socket.close()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 355, in close
    self.ws_connection.close(code, reason)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 975, in close
    self._write_frame(True, 0x8, close_data)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 768, in _write_frame
    return self.stream.write(frame)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 406, in write
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError`

`2017-05-14 17:15:48,990 [tornado.general.ERROR] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 523, in _handle_events
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized
2017-05-14 17:15:49,006 [tornado.application.ERROR] Exception in callback None
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 523, in _handle_events
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\buggy\Documents\script-server\execution.py", line 126, in notify_finished
    listener.finished()
  File "C:\Users\buggy\Documents\script-server\launcher.py", line 351, in finished
    web_socket.close()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 355, in close
    self.ws_connection.close(code, reason)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 975, in close
    self._write_frame(True, 0x8, close_data)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\websocket.py", line 768, in _write_frame
    return self.stream.write(frame)
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 406, in write
    self._handle_write()
  File "C:\Users\buggy\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\iostream.py", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
TypeError: 'NoneType' object does not support item deletion`

**Comment by bugy** [comment]
Fixed. It was caused by concurrency issue - tornado requires all the actions to websockets to be done in main IOLoop thread. And previously socket close() method was called from a different thread, which caused these errors on Windows time to time.
