### ISSUE TITLE
 I'm having some issues with deployment

### ISSUE THREAD

**Issue by ciscoivan** [bugy/script-server#738]
[root@localhost conf.json]# docker logs bcaeada23707
2024-02-29 03:28:08,088 [root.INFO] Starting Script Server, v1.18.0
2024-02-29 03:28:08,090 [migrations.INFO] Applying migration add_execution_info_to_log_files
2024-02-29 03:28:08,090 [migrations.INFO] Applying migration introduce_access_config
Traceback (most recent call last):
  File "/app/launcher.py", line 11, in <module>
    main.main()
  File "/app/src/main.py", line 86, in main
    migrations.migrate.migrate(TEMP_FOLDER, CONFIG_FOLDER, SERVER_CONF_PATH, LOG_FOLDER)
  File "/app/src/migrations/migrate.py", line 388, in migrate
    migration_descriptor.callable(context)
  File "/app/src/migrations/migrate.py", line 210, in __introduce_access_config
    content = file_utils.read_file(file_path)
  File "/app/src/utils/file_utils.py", line 63, in read_file
    with open(path, mode, newline=newline) as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/conf/conf.json'
[root@localhost conf.json]#

**Comment by bugy** [comment]
Hi @ciscoivan, the error is `Is a directory: '/app/conf/conf.json'`
So I guess you are assigning folder to file in docker
